import React from 'react';
import { roboto, roboto_mono, roboto_condensed, roboto_flex, courierPrime, inter } from '@/app/fonts';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children } : {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={`${roboto_flex.className} flex flex-col min-h-screen`}>
        {children}
      </body>
    </html>
  );
}
